const vehicles=[['Citroën Ami','Menzil Artırma','Citroën'],['XEV Yoyo','Batarya Değişimi','XEV'],['Renault Twizy','Özel Batarya Paketi','Renault'],['Nissan X-Trail','Batarya Yenileme','Nissan'],['Volta EV1','Menzil Artırma','Volta'],['Volta EV2','Batarya Değişimi','Volta']];
const carHTML=(name)=>`<div class="car ${name==='Citroën Ami'?'ami':''}"><i>${name==='Citroën Ami'?'AMI':name.split(' ')[0]}</i><em>BATERFACE</em></div>`;
function renderProjects(filter='all'){const list=filter==='all'?vehicles:vehicles.filter(v=>v[2]===filter);document.querySelector('#projectGrid').innerHTML=list.map(v=>`<article class="card" data-open="${v[0]}"><div class="card-art">${carHTML(v[0])}</div><div class="card-info"><b>${v[0]}</b><small>${v[1]}</small></div></article>`).join('');document.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>openDetail(x.dataset.open));}
document.querySelector('#featuredCards').innerHTML=vehicles.slice(0,3).map(v=>`<article class="card" data-open="${v[0]}"><div class="card-art">${carHTML(v[0])}</div><div class="card-info"><b>${v[0]}</b><small>${v[1]}</small></div></article>`).join('');
function renderVehicles(){document.querySelector('#vehicleSelect').innerHTML=vehicles.map((v,i)=>`<button class="${i===0?'selected':''}" data-v="${v[0]}">${v[0]}</button>`).join('');document.querySelectorAll('#vehicleSelect button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#vehicleSelect button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});document.querySelectorAll('.type-select button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.type-select button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});}
function openDetail(name){location.hash='detail';document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.querySelector('#detail').classList.add('active');const steps=[['01',name,'Şehir içi ulaşım için tasarlanan kompakt yapı ve özel çözüm yaklaşımı.'],['02','Tampon Sökümü','Orijinal bağlantıları korunarak araç dikkatlice sökülür.'],['03','Batarya Erişimi','Arka bölümdeki mevcut batarya yapısına erişim hazırlanır.'],['04','Ek Batarya Montajı','Araca entegre edilen kompakt batarya paketi hedef menzil için konumlandırılır.'],['05','Montaj','Tüm bağlantılar kontrol edilerek tampon tekrar monte edilir.'],['06','Tamamlanan Proje','Testleri tamamlanan araç teslimata hazırlanır.']];document.querySelector('#timeline').innerHTML=steps.map(s=>`<div class="tstep"><small>${s[0]}</small><h2>${s[1]}</h2><p>${s[2]}</p></div>`).join('');document.querySelector('#batteryLabel').textContent='ORİJİNAL';document.querySelector('#batteryBox').classList.remove('show');const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&e.target.querySelector('h2')?.textContent==='Ek Batarya Montajı'){document.querySelector('#batteryBox').classList.add('show');document.querySelector('#batteryLabel').textContent='BATERFACE';}}),{threshold:.7});document.querySelectorAll('.tstep').forEach(x=>obs.observe(x));}
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));(document.querySelector('#'+id)||document.querySelector('#home')).classList.add('active');document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.dataset.page===id));window.scrollTo(0,0);}
document.querySelectorAll('[data-page]').forEach(x=>x.addEventListener('click',e=>{e.preventDefault();const id=x.dataset.page;history.pushState(null,'','#'+id);showPage(id);document.querySelector('header').classList.remove('open')}));window.addEventListener('popstate',()=>showPage(location.hash.slice(1)||'home'));window.addEventListener('hashchange',()=>{const id=location.hash.slice(1)||'home';if(id!=='detail')showPage(id)});
document.querySelector('.hamb').onclick=()=>document.querySelector('header').classList.toggle('open');document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');renderProjects(b.dataset.filter)});
document.querySelector('#wa').onclick=()=>{const v=document.querySelector('#vehicleSelect .selected')?.dataset.v||'Belirtilmedi';const t=document.querySelector('.type-select .selected')?.textContent||'Belirtilmedi';const d=document.querySelector('#details').value||'Detay belirtilmedi';location.href=`https://wa.me/905XXXXXXXXX?text=${encodeURIComponent('Çözüm Talebi\nAraç: '+v+'\nÇözüm: '+t+'\nDetay: '+d)}`};
renderProjects();renderVehicles();showPage(location.hash.slice(1)||'home');
