const vehicles=[
{name:"Citroën Ami",image:"assets/vehicles/citroen-ami.jpg",battery:"assets/projects/ami/battery.jpg"},
{name:"XEV Yoyo",image:"assets/vehicles/xev-yoyo.jpg",battery:"assets/projects/xev-yoyo/battery.jpg"},
{name:"Renault Twizy",image:"assets/vehicles/renault-twizy.jpg",battery:"assets/projects/twizy/battery.jpg"},
{name:"X-Trail",image:"assets/vehicles/x-trail.jpg",battery:"assets/projects/x-trail/battery.jpg"},
{name:"Volta EV1",image:"assets/vehicles/volta-ev1.jpg",battery:"assets/projects/volta-ev1/battery.jpg"},
{name:"Volta EV2",image:"assets/vehicles/volta-ev2.jpg",battery:"assets/projects/volta-ev2/battery.jpg"}];
let selectedVehicle="",selectedType="";
const vehicleGrid=document.getElementById("vehicle-grid"),typeGrid=document.getElementById("type-grid"),summary=document.getElementById("selection-summary"),details=document.getElementById("project-details"),whatsappBtn=document.getElementById("whatsapp-btn");
vehicles.forEach(v=>{const b=document.createElement("button");b.textContent=v.name;b.onclick=()=>{selectedVehicle=v.name;[...vehicleGrid.children].forEach(x=>x.classList.remove("selected"));b.classList.add("selected");updateSummary()};vehicleGrid.appendChild(b)});
typeGrid.querySelectorAll("button").forEach(b=>b.onclick=()=>{selectedType=b.dataset.type;typeGrid.querySelectorAll("button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");updateSummary()});
function updateSummary(){if(!selectedVehicle||!selectedType){summary.textContent="Araç ve çözüm türü seçilmedi.";whatsappBtn.disabled=true;return}summary.textContent=`${selectedVehicle} · ${selectedType}`;whatsappBtn.disabled=false}
whatsappBtn.onclick=()=>{const phone="905XXXXXXXXX";const message=`Merhaba BaterFace, Çözüm Talebi oluşturmak istiyorum.\n\nAraç: ${selectedVehicle}\nÇözüm: ${selectedType}\nProje detayları: ${details.value||"Belirtilmedi"}\n\nDetaylı bilgi ve fiyat almak istiyorum.`;window.open(`https://wa.me/${phone}?text=${encodeURIComponent(message)}`,"_blank")};
const modal=document.getElementById("vehicle-modal");document.getElementById("suggest-vehicle").onclick=()=>modal.classList.add("show");document.getElementById("modal-close").onclick=()=>modal.classList.remove("show");modal.onclick=e=>{if(e.target===modal)modal.classList.remove("show")};document.getElementById("suggestion-send").onclick=()=>{const i=document.getElementById("suggestion-input"),v=i.value.trim();if(!v)return;alert(`"${v}" araç önerisi alındı.`);i.value="";modal.classList.remove("show")};
document.querySelector(".menu-btn").onclick=()=>document.getElementById("nav").classList.toggle("open");document.querySelectorAll(".nav a").forEach(a=>a.onclick=()=>document.getElementById("nav").classList.remove("open"));
const projectSteps=[["01 · ARAÇ","Citroën Ami","Aracın mevcut yapısı incelenir ve uygulama alanları belirlenir",""],["02 · TAMPON SÖKÜMÜ","Tampon Sökümü","Arka tampon ve bağlantıları kontrollü şekilde ayrılır. Gerçek söküm fotoğrafları daha sonra eklenecek.","open"],["03 · EK BATARYA","Ek Batarya","BaterFace ek batarya paketi uygun alana yerleştirilir.","battery"],["04 · MONTAJ","Montaj","Batarya bağlantıları ve montaj elemanları kontrol edilir.","mount"],["05 · TAMAMLANAN PROJE","Tamamlanan Proje","Sistem tamamlanır ve araç kullanıma hazır hale getirilir.","done"]];
const amiVisual=document.querySelector(".ami-visual"),kicker=document.getElementById("ami-kicker"),amiTitle=document.getElementById("ami-title"),amiText=document.getElementById("ami-text"),amiSpecs=document.getElementById("ami-specs");
function setProjectStep(i){const s=projectSteps[i];document.querySelectorAll(".step").forEach((x,n)=>x.classList.toggle("active",n===i));amiVisual.className="ami-visual "+s[3];kicker.textContent=s[0];amiTitle.textContent=s[1];amiText.textContent=s[2];amiSpecs.innerHTML=i>=2?`<div><span>Batarya</span><b>Gerçek görsel daha sonra</b></div><div><span>Kapasite</span><b>Teknik veri daha sonra</b></div><div><span>Montaj</span><b>Araca özel</b></div>`:`<div><span>Proje</span><b>Menzil Artırma</b></div><div><span>Yaklaşım</span><b>Araca özel</b></div>`}
document.querySelectorAll(".step").forEach(b=>b.onclick=()=>setProjectStep(Number(b.dataset.step)));setProjectStep(0);
const amiSection=document.querySelector(".ami-project");if(amiSection)new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;const r=e.boundingClientRect,p=Math.min(.999,Math.max(0,(innerHeight-r.top)/(innerHeight+r.height)));setProjectStep(Math.min(4,Math.floor(p*5)))}),{threshold:[.15,.35,.55,.75]}).observe(amiSection);
document.getElementById("contact-whatsapp").onclick=e=>{e.preventDefault();window.open("https://wa.me/905XXXXXXXXX","_blank")};
